AMREX_HOME := ../..

DEBUG	= FALSE

DIM	= 3

COMP    = gcc

USE_CUDA  = TRUE
USE_HIP   = FALSE
USE_SYCL  = FALSE

include $(AMREX_HOME)/Tools/GNUMake/Make.defs
include ./Make.package
include $(AMREX_HOME)/Src/Make.package
include $(AMREX_HOME)/Tools/GNUMake/Make.rules
