name: clang

on:
  push:
  pull_request:
  schedule:
    - cron: "22 22 * * 6"

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-clang
  cancel-in-progress: true

jobs:
  Tests-gmake:
    name: Clang Tests & GNU Make
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_clang.sh
    - name: Tests
      run: |
        cd Tests/Parser
        make -j4 COMP=clang
        ./main.llvm.ex

        cd ../Parser2
        make -j4 COMP=clang
        ./main.llvm.ex

        cd ../GPU
        make -j4 USE_CPU=TRUE COMP=clang
        ./main.llvm.ex

  Tutorials-gmake:
    name: Clang libamrexpr & GNU Make
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_clang.sh
    - name: Build libamrexpr
      run: |
        ./configure --comp llvm
        make -j4
        make install
    - name: Run
      run: |
        cd Tutorials/libamrexpr
        make -j4 CXX=clang++
        ./a.out

  Tests-cmake:
    name: Clang Tests & CMake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_clang.sh
    - name: Tests
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_COMPILER=clang++ -DENABLE_TESTS=ON
        make -j4 VERBOSE=ON
        ctest --output-on-failure

  Tutorials-cmake:
    name: Clang libamrexpr & CMake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_clang.sh
    - name: Build libamrexpr
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=../installdir
        make -j4 VERBOSE=ON
        make install
        cd ..
    - name: Run
      run: |
        cd Tutorials/libamrexpr
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=$(realpath ../../../installdir) -DCMAKE_CXX_COMPILER=clang++
        make -j4 VEBOSE=ON
        ./parser_test
