name: cuda

on:
  push:
  pull_request:
  schedule:
    - cron: "22 22 * * 6"

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-cuda
  cancel-in-progress: true

jobs:
  Tests-gmake:
    name: CUDA Tests & GNU Make
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_nvcc.sh
    - name: Tests
      run: |
        export PATH=/usr/local/cuda/bin:${PATH}
        export LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
        which nvcc || echo "nvcc not in PATH!"

        cd Tests/GPU
        make -j4 USE_CUDA=TRUE CUDA_ARCH=80

  Tests-cmake:
    name: CUDA Tests & CMake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_nvcc.sh
    - name: Tests
      run: |
        export PATH=/usr/local/cuda/bin:${PATH}
        export LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
        which nvcc || echo "nvcc not in PATH!"

        cmake --version

        mkdir build
        cd build
        cmake .. \
            -DCMAKE_INSTALL_PREFIX=../cuda_installdir \
            -DENABLE_CUDA=ON \
            -DCMAKE_CUDA_ARCHITECTURES=80 \
            -DENABLE_TESTS=ON
        make -j4 VERBOSE=ON
        make install

  Tutorials-cmake:
    name: CUDA Tutorials & CMake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_nvcc.sh
    - name: Tests
      run: |
        export PATH=/usr/local/cuda/bin:${PATH}
        export LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
        which nvcc || echo "nvcc not in PATH!"

        cmake --version

        mkdir build
        cd build
        cmake .. \
            -DCMAKE_INSTALL_PREFIX=../cuda_installdir \
            -DENABLE_CUDA=ON \
            -DCMAKE_CUDA_ARCHITECTURES=80
        make -j4 VERBOSE=ON
        make install

        cd ../Tutorials/libamrexpr
        mkdir build
        cd build
        cmake .. \
            -DCMAKE_PREFIX_PATH=$(realpath ../../../cuda_installdir) \
            -DENABLE_CUDA=ON \
            -DCMAKE_CUDA_ARCHITECTURES=80
        make -j4 VERBOSE=ON
