name: gcc

on:
  push:
  pull_request:
  schedule:
    - cron: "22 22 * * 6"

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-linux-gcc
  cancel-in-progress: true

jobs:
  Tests:
    name: GCC Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_gcc.sh
    - name: Tests
      run: |
        cd Tests/Parser
        make -j4
        ./main.gnu.ex

        cd ../Parser2
        make -j4
        ./main.gnu.ex

        cd ../GPU
        make -j4 USE_CPU=TRUE
        ./main.gnu.ex

  Tutorials:
    name: GCC libamrexpr & GNU Make
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_gcc.sh
    - name: Build libamrexpr
      run: |
        ./configure --comp gnu
        make -j4
        make install
    - name: Run
      run: |
        cd Tutorials/libamrexpr
        make -j4 CXX=g++
        ./a.out

  Tests-cmake:
    name: GCC Tests & CMake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_gcc.sh
    - name: Tests
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_COMPILER=g++ -DENABLE_TESTS=ON
        make -j4 VERBOSE=ON
        ctest --output-on-failure

  Tutorials-gmake:
    name: GCC libamrexpr & GNU Make
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_gcc.sh
    - name: Build libamrexpr
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=../installdir
        make -j4 VERBOSE=ON
        cd ..
    - name: Run
      run: |
        cd Tutorials/libamrexpr
        mkdir build
        cd build
        cmake .. -DCMAKE_PREFIX_PATH=../../installdir -DCMAKE_CXX_COMPILER=g++
        make -j4 VEBOSE=ON
        ./parser_test
