name: GCC

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-linux-gcc
  cancel-in-progress: true

jobs:
  Tests:
    name: GCC Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_gcc.sh
    - name: Tests
      run: |
        cd Tests/Parser
        make -j4
        ./main.gnu.ex

        cd ../GPU
        make -j4 USE_CPU=TRUE
        ./main.gnu.ex
