name: sycl

on:
  push:
  pull_request:
  schedule:
    - cron: "22 22 * * 6"

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-sycl
  cancel-in-progress: true

jobs:
  Tests:
    name: SYCL Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Dependencies
      run: |
        .github/workflows/dependencies/dependencies_dpcpp.sh
    - name: Tests
      run: |
        set +e
        source /opt/intel/oneapi/setvars.sh
        set -e

        cd Tests/GPU
        make -j4 USE_SYCL=TRUE
